services:
  backend-api:
    build: ./backend
    container_name: klemp-backend
    ports:
      - "5002:5000"
    volumes:
      - ./data:/app/data  
    restart: always

  frontend-web:
    build: ./frontend
    container_name: klemp-frontend
    ports:
      - "5001:80"
    depends_on:
      - backend-api
    restart: always